openapi: 3.0.3
info:
  title: DCMS - Document Control Management System API
  description: |
    API documentation for Gacoan Document Control Management System (DCMS).

    ## Authentication
    All API endpoints require authentication using JWT Bearer tokens.

    ## Base URL
    - Development: `http://localhost:3000/api`
    - Production: `https://your-domain.com/api`
  version: 1.0.0
  contact:
    name: DCMS Support
    email: support@miegacoan.id

servers:
  - url: /api
    description: API Server

tags:
  - name: Authentication
    description: User authentication endpoints
  - name: Users
    description: User management endpoints
  - name: Documents
    description: Document management endpoints
  - name: Categories
    description: Document category management
  - name: Departments
    description: Department management
  - name: Positions
    description: Position management
  - name: Approvals
    description: Document approval workflow

paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: User login
      description: Authenticate user and receive access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: admin@miegacoan.id
                password:
                  type: string
                  format: password
                  example: admin123456
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      accessToken:
                        type: string
                      refreshToken:
                        type: string
                      user:
                        $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials

  /auth/logout:
    post:
      tags:
        - Authentication
      summary: User logout
      description: Invalidate current session
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful

  /auth/refresh:
    post:
      tags:
        - Authentication
      summary: Refresh access token
      description: Get new access token using refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Token refreshed successfully
        '401':
          description: Invalid refresh token

  /auth/me:
    get:
      tags:
        - Authentication
      summary: Get current user
      description: Get authenticated user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized

  /users:
    get:
      tags:
        - Users
      summary: List users
      description: Get paginated list of users
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/LimitParam'
        - name: search
          in: query
          schema:
            type: string
        - name: role
          in: query
          schema:
            type: string
            enum: [ADMIN, USER]
        - name: departmentId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUsers'

    post:
      tags:
        - Users
      summary: Create user
      description: Create a new user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created
        '400':
          description: Validation error

  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user by ID
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: User details
        '404':
          description: User not found

    put:
      tags:
        - Users
      summary: Update user
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated
        '404':
          description: User not found

    delete:
      tags:
        - Users
      summary: Delete user
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: User deleted
        '404':
          description: User not found

  /documents:
    get:
      tags:
        - Documents
      summary: List documents
      description: Get paginated list of documents
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/LimitParam'
        - name: search
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum: [DRAFT, IN_REVIEW, APPROVED, ACTIVE, REVISION_REQUIRED, OBSOLETE, ARCHIVED]
        - name: categoryId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of documents

    post:
      tags:
        - Documents
      summary: Create document
      description: Upload and create a new document
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - title
                - categoryId
                - file
              properties:
                title:
                  type: string
                description:
                  type: string
                categoryId:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Document created

  /documents/{id}:
    get:
      tags:
        - Documents
      summary: Get document by ID
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: Document details
        '404':
          description: Document not found

    put:
      tags:
        - Documents
      summary: Update document
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: Document updated

    delete:
      tags:
        - Documents
      summary: Delete document
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      responses:
        '200':
          description: Document deleted

  /categories:
    get:
      tags:
        - Categories
      summary: List categories
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of categories

    post:
      tags:
        - Categories
      summary: Create category
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryRequest'
      responses:
        '201':
          description: Category created

  /departments:
    get:
      tags:
        - Departments
      summary: List departments
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of departments

    post:
      tags:
        - Departments
      summary: Create department
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDepartmentRequest'
      responses:
        '201':
          description: Department created

  /positions:
    get:
      tags:
        - Positions
      summary: List positions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of positions

    post:
      tags:
        - Positions
      summary: Create position
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePositionRequest'
      responses:
        '201':
          description: Position created

  /approvals:
    get:
      tags:
        - Approvals
      summary: List pending approvals
      description: Get list of documents pending approval for current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of pending approvals

  /approvals/{id}/approve:
    post:
      tags:
        - Approvals
      summary: Approve document
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                comments:
                  type: string
      responses:
        '200':
          description: Document approved

  /approvals/{id}/reject:
    post:
      tags:
        - Approvals
      summary: Reject document
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - reason
              properties:
                reason:
                  type: string
      responses:
        '200':
          description: Document rejected

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    IdParam:
      name: id
      in: path
      required: true
      schema:
        type: string

    PageParam:
      name: page
      in: query
      schema:
        type: integer
        default: 1
        minimum: 1

    LimitParam:
      name: limit
      in: query
      schema:
        type: integer
        default: 10
        minimum: 1
        maximum: 100

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        employeeId:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        role:
          type: string
          enum: [ADMIN, USER]
        departmentId:
          type: string
        positionId:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateUserRequest:
      type: object
      required:
        - email
        - name
        - password
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        password:
          type: string
          minLength: 8
        employeeId:
          type: string
        role:
          type: string
          enum: [ADMIN, USER]
        departmentId:
          type: string
        positionId:
          type: string

    UpdateUserRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        employeeId:
          type: string
        role:
          type: string
          enum: [ADMIN, USER]
        departmentId:
          type: string
        positionId:
          type: string
        isActive:
          type: boolean

    PaginatedUsers:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/User'
        pagination:
          $ref: '#/components/schemas/Pagination'

    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        totalPages:
          type: integer

    CreateCategoryRequest:
      type: object
      required:
        - name
        - code
      properties:
        name:
          type: string
        code:
          type: string
        description:
          type: string
        prefix:
          type: string

    CreateDepartmentRequest:
      type: object
      required:
        - name
        - code
      properties:
        name:
          type: string
        code:
          type: string
        description:
          type: string

    CreatePositionRequest:
      type: object
      required:
        - name
        - code
      properties:
        name:
          type: string
        code:
          type: string
        departmentId:
          type: string
        level:
          type: integer
        description:
          type: string
